name: "reddit"
mode: "dev"
port: 8080
version: "v0.0.2"
start_time: "2023-09-16"
machine_id: 1
app:
  name: "reddit"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "reddit.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password : "123456"
  dbname: "reddit"
  max_open_conns: 200
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 100